name: multiple-perfmon-influx-exporter
services:
  perfmon_15-1:
    image: sieteunoseis/perfmon-influx-exporter:latest
    command:
      - start
    environment:
      - INFLUXDB_BUCKET=perfmon_15_1      
      - PM_INTERVAL=15000
      - PM_OBJECT_COLLECT_ALL=Cisco CallManager,Cisco CallManager System Performance,Cisco HW Conference Bridge Device,Cisco LDAP Directory,Cisco Lines,Cisco Media Streaming App,Cisco MOH Device,Cisco MTP Device,Cisco Phones,Cisco Signaling,Cisco SIP,Cisco SIP Line Normalization,Cisco SIP Normalization,Cisco SIP Stack,Cisco SIP Station
      - PM_OBJECT_SESSION_PERCENTAGE=Memory,Processor
      - PM_OBJECT_SESSION_PERCENTAGE_SLEEP=15000
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env
  perfmon_15-2:
    image: sieteunoseis/perfmon-influx-exporter:latest
    command:
      - start
    environment:
      - INFLUXDB_BUCKET=perfmon_15_1
      - PM_DELAYED_START=15000      
      - PM_INTERVAL=15000
      - PM_OBJECT_COLLECT_ALL=IP,IP6,Memory,Network Interface,Number of Replicates Created and State of Replication,Partition,Process,Ramfs,SAML SSO,System,TCP,Thread
      - PM_OBJECT_SESSION_PERCENTAGE=Process,Partition,Thread
      - PM_OBJECT_SESSION_PERCENTAGE_SLEEP=15000
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env
